package com.wgl.ssm.web.dao;

import com.wgl.ssm.model.entitys.CifUser;

public interface CifUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    int insert(CifUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    int insertSelective(CifUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    CifUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CifUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cif_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CifUser record);
}