package com.wgl.ssm.model.entitys;

import java.util.Date;

public class CifUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.user_img_url
     *
     * @mbggenerated
     */
    private String userImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.cell
     *
     * @mbggenerated
     */
    private String cell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.birth_day
     *
     * @mbggenerated
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.register_source_id
     *
     * @mbggenerated
     */
    private Integer registerSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.recommand_id
     *
     * @mbggenerated
     */
    private String recommandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.gmt_register
     *
     * @mbggenerated
     */
    private Date gmtRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.gmt_last_login
     *
     * @mbggenerated
     */
    private Date gmtLastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cif_user.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.ID
     *
     * @return the value of cif_user.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.ID
     *
     * @param id the value for cif_user.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.user_id
     *
     * @return the value of cif_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.user_id
     *
     * @param userId the value for cif_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.user_type
     *
     * @return the value of cif_user.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.user_type
     *
     * @param userType the value for cif_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.user_img_url
     *
     * @return the value of cif_user.user_img_url
     *
     * @mbggenerated
     */
    public String getUserImgUrl() {
        return userImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.user_img_url
     *
     * @param userImgUrl the value for cif_user.user_img_url
     *
     * @mbggenerated
     */
    public void setUserImgUrl(String userImgUrl) {
        this.userImgUrl = userImgUrl == null ? null : userImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.nick_name
     *
     * @return the value of cif_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.nick_name
     *
     * @param nickName the value for cif_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.real_name
     *
     * @return the value of cif_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.real_name
     *
     * @param realName the value for cif_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.cell
     *
     * @return the value of cif_user.cell
     *
     * @mbggenerated
     */
    public String getCell() {
        return cell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.cell
     *
     * @param cell the value for cif_user.cell
     *
     * @mbggenerated
     */
    public void setCell(String cell) {
        this.cell = cell == null ? null : cell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.gender
     *
     * @return the value of cif_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.gender
     *
     * @param gender the value for cif_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.birth_day
     *
     * @return the value of cif_user.birth_day
     *
     * @mbggenerated
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.birth_day
     *
     * @param birthDay the value for cif_user.birth_day
     *
     * @mbggenerated
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.status
     *
     * @return the value of cif_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.status
     *
     * @param status the value for cif_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.register_source_id
     *
     * @return the value of cif_user.register_source_id
     *
     * @mbggenerated
     */
    public Integer getRegisterSourceId() {
        return registerSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.register_source_id
     *
     * @param registerSourceId the value for cif_user.register_source_id
     *
     * @mbggenerated
     */
    public void setRegisterSourceId(Integer registerSourceId) {
        this.registerSourceId = registerSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.recommand_id
     *
     * @return the value of cif_user.recommand_id
     *
     * @mbggenerated
     */
    public String getRecommandId() {
        return recommandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.recommand_id
     *
     * @param recommandId the value for cif_user.recommand_id
     *
     * @mbggenerated
     */
    public void setRecommandId(String recommandId) {
        this.recommandId = recommandId == null ? null : recommandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.id_card
     *
     * @return the value of cif_user.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.id_card
     *
     * @param idCard the value for cif_user.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.gmt_register
     *
     * @return the value of cif_user.gmt_register
     *
     * @mbggenerated
     */
    public Date getGmtRegister() {
        return gmtRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.gmt_register
     *
     * @param gmtRegister the value for cif_user.gmt_register
     *
     * @mbggenerated
     */
    public void setGmtRegister(Date gmtRegister) {
        this.gmtRegister = gmtRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.gmt_last_login
     *
     * @return the value of cif_user.gmt_last_login
     *
     * @mbggenerated
     */
    public Date getGmtLastLogin() {
        return gmtLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.gmt_last_login
     *
     * @param gmtLastLogin the value for cif_user.gmt_last_login
     *
     * @mbggenerated
     */
    public void setGmtLastLogin(Date gmtLastLogin) {
        this.gmtLastLogin = gmtLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.gmt_create
     *
     * @return the value of cif_user.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.gmt_create
     *
     * @param gmtCreate the value for cif_user.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.gmt_modified
     *
     * @return the value of cif_user.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.gmt_modified
     *
     * @param gmtModified the value for cif_user.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cif_user.memo
     *
     * @return the value of cif_user.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cif_user.memo
     *
     * @param memo the value for cif_user.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}